In [2]:
import torch
import neural_utils as nu

model = nu.FCN(1,1,4,2)

for i, p in enumerate(model.parameters()):
    print(f"Parameter {i}")
    print("shape:", p.shape)
    print(p)
    print()


Parameter 0
shape: torch.Size([4, 1])
Parameter containing:
tensor([[-0.0597],
        [-0.6625],
        [-0.3793],
        [ 0.9605]], requires_grad=True)

Parameter 1
shape: torch.Size([4])
Parameter containing:
tensor([-0.4045, -0.4786,  0.7140, -0.2548], requires_grad=True)

Parameter 2
shape: torch.Size([4, 4])
Parameter containing:
tensor([[ 0.0651,  0.1232, -0.0902, -0.4664],
        [ 0.3254, -0.0333,  0.1565, -0.3666],
        [-0.4873,  0.3573,  0.3793, -0.3217],
        [ 0.1415,  0.1639,  0.3382, -0.2620]], requires_grad=True)

Parameter 3
shape: torch.Size([4])
Parameter containing:
tensor([-0.1980, -0.1092,  0.2347,  0.3521], requires_grad=True)

Parameter 4
shape: torch.Size([1, 4])
Parameter containing:
tensor([[-0.1164,  0.1852, -0.3610,  0.2246]], requires_grad=True)

Parameter 5
shape: torch.Size([1])
Parameter containing:
tensor([-0.3655], requires_grad=True)



In [3]:
print(model.state_dict())

OrderedDict({'net.0.weight': tensor([[-0.0597],
        [-0.6625],
        [-0.3793],
        [ 0.9605]]), 'net.0.bias': tensor([-0.4045, -0.4786,  0.7140, -0.2548]), 'net.2.weight': tensor([[ 0.0651,  0.1232, -0.0902, -0.4664],
        [ 0.3254, -0.0333,  0.1565, -0.3666],
        [-0.4873,  0.3573,  0.3793, -0.3217],
        [ 0.1415,  0.1639,  0.3382, -0.2620]]), 'net.2.bias': tensor([-0.1980, -0.1092,  0.2347,  0.3521]), 'net.4.weight': tensor([[-0.1164,  0.1852, -0.3610,  0.2246]]), 'net.4.bias': tensor([-0.3655])})


In [19]:
import loss_landscape as ll
from importlib import reload 

reload(ll)


direction = ll.create_random_direction(model, dir_type='weights', norm='filter', ignore=['bias'])

for param, dir in zip(model.parameters(), direction[0]):
    print(param)
    print(param.data)
    print(param.data.shape == dir.shape)

Parameter containing:
tensor([[-0.0597],
        [-0.6625],
        [-0.3793],
        [ 0.9605]], requires_grad=True)
tensor([[-0.0597],
        [-0.6625],
        [-0.3793],
        [ 0.9605]])
True
Parameter containing:
tensor([-0.4045, -0.4786,  0.7140, -0.2548], requires_grad=True)
tensor([-0.4045, -0.4786,  0.7140, -0.2548])
True
Parameter containing:
tensor([[ 0.0651,  0.1232, -0.0902, -0.4664],
        [ 0.3254, -0.0333,  0.1565, -0.3666],
        [-0.4873,  0.3573,  0.3793, -0.3217],
        [ 0.1415,  0.1639,  0.3382, -0.2620]], requires_grad=True)
tensor([[ 0.0651,  0.1232, -0.0902, -0.4664],
        [ 0.3254, -0.0333,  0.1565, -0.3666],
        [-0.4873,  0.3573,  0.3793, -0.3217],
        [ 0.1415,  0.1639,  0.3382, -0.2620]])
True
Parameter containing:
tensor([-0.1980, -0.1092,  0.2347,  0.3521], requires_grad=True)
tensor([-0.1980, -0.1092,  0.2347,  0.3521])
True
Parameter containing:
tensor([[-0.1164,  0.1852, -0.3610,  0.2246]], requires_grad=True)
tensor([[-0.1164,  